### PR TITLE
[Bahasa Indonesia] Panduan pembaruan untuk pemula.md

### PR DESCRIPTION
**Pull request by XMFile**
This is intended for those who don't understand English.

### CODE REVIEW

**Comment by KobeW50** [comment]
Thank you for your contribution! Please make the changes to a new file so that the current English version isn't overwritten.

**Review by Spacellary — CHANGES_REQUESTED** [review]
This needs to be added under a new file as to not overwrite the current English guide.

**Comment by Spacellary** [comment]
Thanks for the translation.

---

Added in commit: https://github.com/ReVanced-Extended-Community/Community-Guides/commit/f4117b9de9fb2114bf1b715fd69a203c2fcf8884

File: [community-wiki/[Bahasa-Indonesia]guide-for-beginners.md](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/%5BBahasa-Indonesia%5Dguide-for-beginners.md)

---

✅

**Comment by KobeW50** [comment]
@Spacellary if you feel it is appropriate, you can link the guide in the subreddit wiki and discord

**Pull request closed without merging**
